"""Initial schema

Revision ID: 55173013013c
Revises: 
Create Date: 2026-08-25 21:58:28.161001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55173013013c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_sites',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('capacity_households', sa.Integer(), nullable=False),
    sa.Column('capacity_people', sa.Integer(), nullable=False),
    sa.Column('available_capacity', sa.Integer(), nullable=False),
    sa.Column('water_availability', sa.Boolean(), nullable=True),
    sa.Column('electricity_availability', sa.Boolean(), nullable=True),
    sa.Column('healthcare_access', sa.Boolean(), nullable=True),
    sa.Column('road_accessibility', sa.Boolean(), nullable=True),
    sa.Column('shelter_availability', sa.Boolean(), nullable=True),
    sa.Column('flood_risk', sa.Float(), nullable=True),
    sa.Column('landslide_risk', sa.Float(), nullable=True),
    sa.Column('earthquake_risk', sa.Float(), nullable=True),
    sa.Column('overall_safety_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'LIMITED', 'UNSAFE', 'FULL', name='sitestatus'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_sites_district'), 'candidate_sites', ['district'], unique=False)
    op.create_index(op.f('ix_candidate_sites_id'), 'candidate_sites', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_sites_name'), 'candidate_sites', ['name'], unique=False)
    op.create_index(op.f('ix_candidate_sites_state'), 'candidate_sites', ['state'], unique=False)
    op.create_table('habitations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('block', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('total_population', sa.Integer(), nullable=False),
    sa.Column('vulnerable_population', sa.Integer(), nullable=False),
    sa.Column('households', sa.Integer(), nullable=False),
    sa.Column('primary_hazard', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('priority_level', sa.Enum('P1', 'P2', 'P3', name='prioritylevel'), nullable=True),
    sa.Column('evacuation_status', sa.Enum('PENDING', 'ROUTING', 'MONITORED', 'COMPLETED', name='evacuationstatus'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habitations_district'), 'habitations', ['district'], unique=False)
    op.create_index(op.f('ix_habitations_id'), 'habitations', ['id'], unique=False)
    op.create_index(op.f('ix_habitations_name'), 'habitations', ['name'], unique=False)
    op.create_index(op.f('ix_habitations_state'), 'habitations', ['state'], unique=False)
    op.create_table('relocation_plans',
    sa.Column('source_habitation_id', sa.UUID(), nullable=False),
    sa.Column('total_population', sa.Integer(), nullable=False),
    sa.Column('vulnerable_population', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY_FOR_REVIEW', 'APPROVED', 'EXECUTED', name='relocationstatus'), nullable=True),
    sa.Column('total_travel_time', sa.Float(), nullable=True),
    sa.Column('coverage_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_habitation_id'], ['habitations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relocation_plans_id'), 'relocation_plans', ['id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('habitation_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='risklevel'), nullable=False),
    sa.Column('hazard_type', sa.String(), nullable=False),
    sa.Column('hazard_exposure', sa.Float(), nullable=False),
    sa.Column('terrain_factor', sa.Float(), nullable=False),
    sa.Column('population_vulnerability', sa.Float(), nullable=False),
    sa.Column('infrastructure_vulnerability', sa.Float(), nullable=False),
    sa.Column('accessibility_factor', sa.Float(), nullable=False),
    sa.Column('historical_exposure', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('primary_driver', sa.String(), nullable=True),
    sa.Column('assessment_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['habitation_id'], ['habitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    op.create_table('site_assessments',
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=False),
    sa.Column('capacity_score', sa.Float(), nullable=False),
    sa.Column('accessibility_score', sa.Float(), nullable=False),
    sa.Column('infrastructure_score', sa.Float(), nullable=False),
    sa.Column('community_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Enum('SAFE', 'RECOMMENDED', 'UNSAFE', 'REQUIRES_REVIEW', name='recommendation'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['candidate_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_assessments_id'), 'site_assessments', ['id'], unique=False)
    op.create_table('allocations',
    sa.Column('relocation_plan_id', sa.UUID(), nullable=False),
    sa.Column('candidate_site_id', sa.UUID(), nullable=False),
    sa.Column('population_allocated', sa.Integer(), nullable=False),
    sa.Column('vulnerable_population_allocated', sa.Integer(), nullable=False),
    sa.Column('travel_time_minutes', sa.Float(), nullable=True),
    sa.Column('allocation_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_site_id'], ['candidate_sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['relocation_plan_id'], ['relocation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_id'), 'allocations', ['id'], unique=False)
    op.create_table('decision_receipts',
    sa.Column('relocation_plan_id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('decision_summary', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('primary_reason', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['relocation_plan_id'], ['relocation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relocation_plan_id')
    )
    op.create_index(op.f('ix_decision_receipts_id'), 'decision_receipts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_receipts_id'), table_name='decision_receipts')
    op.drop_table('decision_receipts')
    op.drop_index(op.f('ix_allocations_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_site_assessments_id'), table_name='site_assessments')
    op.drop_table('site_assessments')
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_relocation_plans_id'), table_name='relocation_plans')
    op.drop_table('relocation_plans')
    op.drop_index(op.f('ix_habitations_state'), table_name='habitations')
    op.drop_index(op.f('ix_habitations_name'), table_name='habitations')
    op.drop_index(op.f('ix_habitations_id'), table_name='habitations')
    op.drop_index(op.f('ix_habitations_district'), table_name='habitations')
    op.drop_table('habitations')
    op.drop_index(op.f('ix_candidate_sites_state'), table_name='candidate_sites')
    op.drop_index(op.f('ix_candidate_sites_name'), table_name='candidate_sites')
    op.drop_index(op.f('ix_candidate_sites_id'), table_name='candidate_sites')
    op.drop_index(op.f('ix_candidate_sites_district'), table_name='candidate_sites')
    op.drop_table('candidate_sites')
    # ### end Alembic commands ###
