"""Add phase 3 domain foundation

Revision ID: dacf228837ce
Revises: 55173013013c
Create Date: 2026-08-26 11:36:51.313335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacf228837ce'
down_revision: Union[str, Sequence[str], None] = '55173013013c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hazards',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('affected_area', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='check_hazard_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='check_hazard_longitude_range'),
    sa.CheckConstraint('severity >= 0 AND severity <= 100', name='check_severity_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hazards_id'), 'hazards', ['id'], unique=False)
    op.create_index(op.f('ix_hazards_type'), 'hazards', ['type'], unique=False)
    op.create_table('site_hazard_exposures',
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('hazard_type', sa.String(), nullable=False),
    sa.Column('exposure_score', sa.Float(), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('exposure_score >= 0 AND exposure_score <= 100', name='check_exposure_score_range'),
    sa.ForeignKeyConstraint(['site_id'], ['candidate_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_hazard_exposures_id'), 'site_hazard_exposures', ['id'], unique=False)
    op.add_column('allocations', sa.Column('source_habitation_id', sa.UUID(), nullable=True))
    op.add_column('allocations', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('allocations', sa.Column('site_score', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'allocations', 'habitations', ['source_habitation_id'], ['id'], ondelete='RESTRICT')
    op.add_column('candidate_sites', sa.Column('accessibility_score', sa.Float(), nullable=True))
    op.add_column('candidate_sites', sa.Column('infrastructure_score', sa.Float(), nullable=True))
    op.add_column('candidate_sites', sa.Column('healthcare_score', sa.Float(), nullable=True))
    op.add_column('candidate_sites', sa.Column('community_score', sa.Float(), nullable=True))
    op.create_check_constraint('check_accessibility_score_range', 'candidate_sites', 'accessibility_score >= 0 AND accessibility_score <= 100')
    op.create_check_constraint('check_available_capacity_limit', 'candidate_sites', 'available_capacity <= capacity_people')
    op.create_check_constraint('check_available_capacity_positive', 'candidate_sites', 'available_capacity >= 0')
    op.create_check_constraint('check_community_score_range', 'candidate_sites', 'community_score >= 0 AND community_score <= 100')
    op.create_check_constraint('check_healthcare_score_range', 'candidate_sites', 'healthcare_score >= 0 AND healthcare_score <= 100')
    op.create_check_constraint('check_infrastructure_score_range', 'candidate_sites', 'infrastructure_score >= 0 AND infrastructure_score <= 100')
    op.create_check_constraint('check_safety_score_range', 'candidate_sites', 'overall_safety_score >= 0 AND overall_safety_score <= 100')
    op.create_check_constraint('check_site_latitude_range', 'candidate_sites', 'latitude >= -90 AND latitude <= 90')
    op.create_check_constraint('check_site_longitude_range', 'candidate_sites', 'longitude >= -180 AND longitude <= 180')
    op.create_check_constraint('check_total_capacity_positive', 'candidate_sites', 'capacity_people >= 0')
    op.add_column('habitations', sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='risklevel'), nullable=True))
    op.create_check_constraint('check_latitude_range', 'habitations', 'latitude >= -90 AND latitude <= 90')
    op.create_check_constraint('check_longitude_range', 'habitations', 'longitude >= -180 AND longitude <= 180')
    op.create_check_constraint('check_population_positive', 'habitations', 'total_population >= 0')
    op.create_check_constraint('check_risk_score_range', 'habitations', 'risk_score >= 0 AND risk_score <= 100')
    op.create_check_constraint('check_vuln_population_less_than_total', 'habitations', 'vulnerable_population <= total_population')
    op.create_check_constraint('check_vuln_population_positive', 'habitations', 'vulnerable_population >= 0')
    op.add_column('relocation_plans', sa.Column('allocated_population', sa.Integer(), nullable=False))
    op.add_column('relocation_plans', sa.Column('uncovered_population', sa.Integer(), nullable=True))
    op.add_column('relocation_plans', sa.Column('rejected_sites', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relocation_plans', 'rejected_sites')
    op.drop_column('relocation_plans', 'uncovered_population')
    op.drop_column('relocation_plans', 'allocated_population')
    op.drop_constraint('check_vuln_population_positive', 'habitations', type_='check')
    op.drop_constraint('check_vuln_population_less_than_total', 'habitations', type_='check')
    op.drop_constraint('check_risk_score_range', 'habitations', type_='check')
    op.drop_constraint('check_population_positive', 'habitations', type_='check')
    op.drop_constraint('check_longitude_range', 'habitations', type_='check')
    op.drop_constraint('check_latitude_range', 'habitations', type_='check')
    op.drop_column('habitations', 'risk_level')
    op.drop_constraint('check_total_capacity_positive', 'candidate_sites', type_='check')
    op.drop_constraint('check_site_longitude_range', 'candidate_sites', type_='check')
    op.drop_constraint('check_site_latitude_range', 'candidate_sites', type_='check')
    op.drop_constraint('check_safety_score_range', 'candidate_sites', type_='check')
    op.drop_constraint('check_infrastructure_score_range', 'candidate_sites', type_='check')
    op.drop_constraint('check_healthcare_score_range', 'candidate_sites', type_='check')
    op.drop_constraint('check_community_score_range', 'candidate_sites', type_='check')
    op.drop_constraint('check_available_capacity_positive', 'candidate_sites', type_='check')
    op.drop_constraint('check_available_capacity_limit', 'candidate_sites', type_='check')
    op.drop_constraint('check_accessibility_score_range', 'candidate_sites', type_='check')
    op.drop_column('candidate_sites', 'community_score')
    op.drop_column('candidate_sites', 'healthcare_score')
    op.drop_column('candidate_sites', 'infrastructure_score')
    op.drop_column('candidate_sites', 'accessibility_score')
    op.drop_constraint(None, 'allocations', type_='foreignkey')
    op.drop_column('allocations', 'site_score')
    op.drop_column('allocations', 'distance_km')
    op.drop_column('allocations', 'source_habitation_id')
    op.drop_index(op.f('ix_site_hazard_exposures_id'), table_name='site_hazard_exposures')
    op.drop_table('site_hazard_exposures')
    op.drop_index(op.f('ix_hazards_type'), table_name='hazards')
    op.drop_index(op.f('ix_hazards_id'), table_name='hazards')
    op.drop_table('hazards')
    # ### end Alembic commands ###
